name: Deployment
on:
  push:
    branches:
      - master
jobs:
  Test:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v2
      - run: npm i
      - run: npm run test
  Deploy:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - run: docker build -t yandex-schedule .
      - run: docker stop yandex-schedule
      - run: docker run --name yandex-schedule --rm -d -p 3001:3000 yandex-schedule
