name: CI
uses: actions/checkout@v2
on:
  push:
    branches:
      - master
jobs:
  test:
    runs-on: self-hosted
    steps:
      - run: cd /usr/src/Yandex-Schedule && git pull
      - run: docker build -t yandex-schedule .
      - run: docker run --name yandex-schedule --rm -p 3000:3000 yandex-schedule